awx-deploy-diff: prevent git pull when DONT_PULL when the environment variable is defined
  @ 00:04 hs

diff --git a/awx-deploy-diff b/awx-deploy-diff
--- a/awx-deploy-diff
+++ b/awx-deploy-diff
@@ -82,7 +82,12 @@ REVISION_TYPE="$(git cat-file -t "$REVISION")"
 if [[ "$REVISION_TYPE" != 'tag' ]]
 then
 
-  git pull                 || die "FAILED TO PULL $REVISION"
+  if [[ -n "$DONT_PULL" ]]
+  then
+
+    git pull               || die "FAILED TO PULL $REVISION"
+
+  fi
 
 fi
 
