awx-deploy-revision: validate SCHEDULE_LIMIT defined in deploy/schedule.awx to avoid incorrect limit
  @ 00:45 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -396,6 +396,14 @@ then
   while read -r SCHEDULE_JOB_TEMPLATE SCHEDULE_LIMIT SCHEDULE_NAME
   do
 
+    SCHEDULE_JSON="job_template/${SCHEDULE_JOB_TEMPLATE}.json"
+    SCHEDULE_INVENTORY="$(jq -r '.[].inventory' "$SCHEDULE_JSON")"
+    stderror "GET INVENTORY $SCHEDULE_INVENTORY FROM $SCHEDULE_JSON"
+    [[ -z "$SCHEDULE_INVENTORY" ]] && die "EMPTY INVENTORY FOR $SCHEDULE_JSON"
+
+    validate_limit "$SCHEDULE_INVENTORY" "$SCHEDULE_LIMIT" \
+      || die "INVALID LIMIT $SCHEDULE_LIMIT FOR $SCHEDULE_JOB_TEMPLATE"
+
 		S_ID="$(schedule_get_id "$SCHEDULE_JOB_TEMPLATE" "$SCHEDULE_NAME")"
     if [[ -z "$S_ID" ]]
     then
