awx-deploy-revision: send inventory from deploy/update.awx
  @ 00:10 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -84,6 +84,14 @@ do
 
 done
 
+grep ^inventory "$DEPLOY_FILE" | sort | while read -r INVENTORY
+do
+
+  [[ -e "$INVENTORY" ]] || die "NOT FOUND FILE $INVENTORY"
+  awx-cli send "$INVENTORY"
+
+done
+
 grep ^job_template "$DEPLOY_FILE" | sort | while read -r JOB_TEMPLATE
 do
 
