awx-deploy-revision: search and send workflows defined in deploy file
  @ 00:05 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -187,6 +187,17 @@ do
 
 done
 
+grep ^workflow "$DEPLOY_FILE" | sort | while read -r WORKFLOW
+do
+
+  [[ -e "$WORKFLOW" ]] || die "NOT FOUND FILE $WORKFLOW"
+
+  echo "SEND WORKFLOW $WORKFLOW"
+  echo "awx-cli send $WORKFLOW" | bash \
+    || die "FAILED SEND WORKFLOW $WORKFLOW"
+
+done
+
 fi
 
 TEAM_ASSOCIATE="$DEPLOY_DIR/team-associate.awx"
