common: add awx-common
  @ 00:05 hs

diff --git a/awx-common b/awx-common
--- a/awx-common
+++ b/awx-common
@@ -29,7 +29,15 @@ die ()
 
 log ()
 {
-  printf "%s\n" "${NORMAL}[INFO] $1 $NORMAL"
+  local NOW
+  NOW="$(date +'%F %T')"
+  printf "%s\n" "${NORMAL}${NOW} [INFO] $1 $NORMAL"
+}
+
+log_send_file()
+{
+  MAX_COLS="$(tput cols)"
+  echo "SEND $1 to $AWX_CFG_HOST *****"
 }
 
 success ()
@@ -60,12 +68,36 @@ do
     | sed 's/awx-cli/ansibel-tower-cli/g'
 done
 
+markdown()
+{
+cat << EOF
+---
+fontsize: 8pt
+code-block-font-size: 8pt
+classoption: landscape
+---
+EOF
+}
+
+code()
+{
+  printf "\\n\\n%s\\n\\n" '```'
+}
+
+title1()
+{
+  printf "\\n# %s\\n\\n" "$1"
+}
+
 get_file_list()
 {
+  local DIR
+  DIR='.'
 
   [[ -z "$1" ]] && exit 1
+  [[ ! -z "$2" ]] && DIR="$2"
 
-  find . -type f -iname "$1" | cut -c 3- | while read -r FILE
+  find -L "$DIR" -type f -iname "$1" | while read -r FILE
   do
     echo "$FILE"
   done
@@ -75,21 +107,44 @@ get_file_list()
 filelist_projects()
 {
 
-  get_file_list 'ansible*.json'
+  get_file_list "$PROJECT_PREFIX*.json" "$DIR_PROJECT"
+
+}
+
+filelist_inventory()
+{
+  [[ -d "$DIR_INVENTORY" ]] || die "NOT FOUND $PWD/$DIR_INVENTORY"
+
+  get_file_list '*.json' "$DIR_INVENTORY"
 
 }
 
 filelist_job_templates()
 {
 
-  get_file_list 'job_template*.json'
+  get_file_list "$JOB_TEMPLATE_PREFIX*.json" "$DIR_JOB_TEMPLATE"
 
 }
 
 filelist_workflows()
 {
 
-  get_file_list 'workflow*.json'
+  get_file_list "$WORKFLOW_PREFIX*.json" "$DIR_WORKFLOW"
+
+}
+
+filelist_send_all()
+{
+  local FILE
+
+  [[   -z "$1" ]] && exit 1
+  [[ ! -e "$1" ]] && exit 1
+
+  cat "$1" | while read -r FILE
+  do
+    log_send_file "$FILE"
+    echo awx-cli send $AWX_DEBUG "$FILE" | bash
+  done
 
 }
 
@@ -218,3 +273,92 @@ awx_ad_hoc_shell_footer
 
 }
 
+awx_cfg_get_host()
+{
+
+grep host "$HOME/.tower_cli.cfg" | cut -d= -f2 | tr -d ' '
+
+}
+
+wait_seconds()
+{
+  local S
+  S=5
+
+  [[ ! -z "$2" ]] && S="$2"
+
+  for i in $(seq $S -1 0)
+  do
+    echo "wait $i seconds to find and send all $1... "
+    sleep 1
+  done
+}
+
+filelist_total()
+{
+  local TOTAL
+
+  TOTAL="$(wc -l "$1" | cut -d' ' -f1)"
+  printf "found %s %s\n" "$TOTAL" "$2"
+}
+
+function get_json()
+{
+  local JSON
+  local NAME
+  local NOW
+  local BAK
+
+  mkdir -p "$1"
+  NAME="$(echo "$2" | tr '/' '-')"
+  JSON="$1/$NAME.json"
+  NOW="$(date +%s)"
+  BAK="$1/$NAME.json.$NOW.bak"
+
+  if [[ -e "$JSON" ]]
+  then
+    stderror "ALREADY EXISTS $JSON"
+    echo "BACKUP $JSON TO $BAK"
+    mv "$JSON" "$BAK"
+  fi
+
+  >&2 echo "RECEIVE $JSON"
+  awx-cli receive --$1 "$2" > "$JSON"
+}
+
+function get_json_workflows()
+{
+  local FILE
+
+  awx-json-get-unified-job-name "$1" \
+    | grep "$WORKFLOW_PREFIX" \
+    | while read -r FILE
+      do
+        get_json_workflows "$DIR_WORKFLOW/$FILE.json"
+      done
+
+  echo "$1"
+}
+
+function get_url()
+{
+  local PATH
+
+  [[ "$1" = 'project'      ]] && PATH='#/projects/'
+  [[ "$1" = 'job_template' ]] && PATH='#/templates/job_template'
+  [[ "$1" = 'workflow'     ]] && PATH='#/templates/workflow_job_template'
+
+  printf "%s/%s/%s" "$AWX_CFG_HOST" "$PATH" "$2"
+}
+
+project_get_id()
+{
+  [[ -z "$1" ]] || awx-cli project get -n "$1" -f id
+}
+
+job_template_get_id()
+{
+  [[ -z "$1" ]] || awx-cli job_template get -n "$1" -f id
+}
+
+AWX_CFG_HOST="$(awx_cfg_get_host)"
