awx-deploy-revision: prevent execute git pull and git fetch --tags when DONT_PULL and DONT_FETCH_TAGS are enabled
  @ 00:35 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -52,8 +52,10 @@ exit 0
 AWX_DIR="$1"
 REVISION="$2"
 DEPLOY_TYPE='update'
-[[ -n "$REGEX_VERSION"  ]] || REGEX_VERSION='v[0-9]+\.[0-9]+\.[0-9]+'
-[[ -n "$REGEX_REVISION" ]] || REGEX_REVISION='(master|release|hotfix|tag)'
+[[ -n "$REGEX_VERSION"   ]] || REGEX_VERSION='v[0-9]+\.[0-9]+\.[0-9]+'
+[[ -n "$REGEX_REVISION"  ]] || REGEX_REVISION='(master|release|hotfix|tag)'
+[[ -n "$DONT_PULL"       ]] || DONT_PULL=0
+[[ -n "$DONT_FETCH_TAGS" ]] || DONT_FETCH_TAGS=0
 
 [[ -z "$1"              ]] && die "EMPTY AWX DIR"
 [[ -z "$2"              ]] && die "EMPTY REVISION"
@@ -85,9 +87,24 @@ REVISION_BRANCH="${REVISION%%/*}"
 if [[ "$REVISION_TYPE" != 'tag' ]]
 then
 
-  # FIXME fatal: refusing to merge unrelated histories
-  git pull --allow-unrelated-histories origin "$REVISION" \
-    || die "FAILED TO PULL $REVISION"
+  if [[ "$DONT_PULL" -eq 0 ]]
+  then
+
+    # FIXME fatal: refusing to merge unrelated histories
+    git pull --allow-unrelated-histories "$ORIGIN" "$REVISION" \
+      || die "FAILED TO PULL $REVISION"
+
+  fi
+
+else
+
+  REVISION_BRANCH='tag'
+  if [[ "$DONT_FETCH_TAGS" -eq 0 ]]
+  then
+
+    git fetch --tags       || die "FAILED TO FETCH TAG $REVISION"
+
+  fi
 
 fi
 
