awx-deploy-revision: replace awx-json-send-job-templates with awx-cli
  @ 00:05 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -78,15 +78,18 @@ git pull                   || die "FAILED TO PULL $REVISION"
 
 grep ^project "$DEPLOY_FILE" | sort | while read -r PROJECT
 do
-  AWX_DEBUG="-vv" && md5sum "$PROJECT" && cat "$PROJECT"
+  cat "$PROJECT"
+  md5sum "$PROJECT"
   [[ -e "$PROJECT" ]] || die "NOT FOUND FILE $PROJECT"
-  echo "awx-cli send -vv $PROJECT" | bash
+  awx-cli send -vv "$PROJECT"
 
 done
 
 grep ^job_template "$DEPLOY_FILE" | sort | while read -r JOB_TEMPLATE
 do
-
-  awx-json-send-job-templates "$JOB_TEMPLATE"
+  cat "$JOB_TEMPLATE"
+  md5sum "$JOB_TEMPLATE"
+  [[ -e "$JOB_TEMPLATE" ]] || die "NOT FOUND FILE $JOB_TEMPLATE"
+  awx-cli send -vv "$JOB_TEMPLATE"
 
 done
