awx-deploy-revision: verify job template documentacion and fail when not found by default (DOC_CHECK=1)
  @ 02:00 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -18,8 +18,21 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
 # shellcheck disable=SC1090
+# shellcheck disable=SC2001
+
 [[ -n "$BASH_DEBUG" ]] && set -x
 DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"
+
+function die()
+{
+  printf "%s\\n" "${RED}[ERROR] $1 $NORMAL"
+  if [[ -n "$DOC_TMP" ]]
+  then
+    echo "CLEAN TEMPORAL FILES IN $DOC_TMP ..."
+    [[ -d "$DOC_TMP" ]] && rm -rf "$DOC_TMP"
+  fi
+  exit 1
+}
 
 function usage()
 {
@@ -56,6 +69,44 @@ DEPLOY_TYPE='update'
 [[ -n "$REGEX_REVISION"  ]] || REGEX_REVISION='(master|release|hotfix|tag)'
 [[ -n "$DONT_PULL"       ]] || DONT_PULL=0
 [[ -n "$DONT_FETCH_TAGS" ]] || DONT_FETCH_TAGS=0
+[[ -n "$DOC_CHECK"       ]] || DOC_CHECK=1
+[[ -n "$DOC_CLONE"       ]] || DOC_CLONE=1
+[[ -n "$DOC_TYPE"        ]] || DOC_TYPE='.md'
+[[ -n "$DOC_SPLIT"       ]] || DOC_SPLIT='_'
+[[ -n "$DOC_JOB_SHORT"   ]] || DOC_JOB_SHORT=1
+
+if [[ -n "$DOC_USER"     ]]
+then
+  [[ -n "$DOC_PASS"      ]] || DOC_PASS="$DOC_USER:$DOC_TOKEN@"
+fi
+
+[[ -n "$DOC_DIR"         ]] || DOC_DIR='/tmp'
+[[ -n "$DOC_PROTO"       ]] || DOC_PROTO='https://'
+[[ -n "$ORIGIN"          ]] || ORIGIN='origin'
+
+if [[ -z "$DOC_URL"      ]]
+then
+
+  if [[ -n "$DOC_HOST"   ]]
+  then
+    if [[ -n "$DOC_REPO" ]]
+    then
+      DOC_URL="${DOC_PROTO}${DOC_PASS}$DOC_HOST/$JOB_GROUP/$DOC_REPO"
+    fi
+  else
+
+URL="$(git remote get-url --all "$ORIGIN" | head -1 | sed 's/>git$//g')"
+GIT="$(echo "$URL" | rev | cut -d/ -f2- | rev)"
+GRP="$(echo "$URL" | rev | cut -d/ -f2  | rev)"
+DOC_URL="$GIT/$GRP.wiki.git"
+
+  fi
+fi
+
+DIR_NAME="$(echo "$PWD" | rev | cut -d/ -f1 | rev)"
+[[ -n "$DOC_TMP"        ]] || DOC_TMP="$DOC_DIR/$DIR_NAME.$(date +%s)"
+MSK_URL="$(echo "$DOC_URL" | sed 's/[a-z\-]\+:[a-zA-Z0-9_\-]\+@//g')"
+[[ -n "$DOC_WIKI"       ]] || DOC_WIKI="${MSK_URL//.wiki.git/\/-\/wikis}"
 
 [[ -z "$1"              ]] && die "EMPTY AWX DIR"
 [[ -z "$2"              ]] && die "EMPTY REVISION"
@@ -223,6 +274,31 @@ grep ^job_template "$DEPLOY_FILE" | sort | while read -r JOB_TEMPLATE
 do
 
   [[ -e "$JOB_TEMPLATE" ]] || die "NOT FOUND FILE $JOB_TEMPLATE"
+
+  JOB_NAME="$(basename "$JOB_TEMPLATE" .json)"
+  JOB_GROUP="/${JOB_NAME%%$DOC_SPLIT*}"
+  JOB_SHORT="$(echo "$JOB_NAME" | sed 's/_v[0-9]\+.[0-9]\+.[0-9]\+//g')"
+  DOC_NAME="$JOB_NAME"
+
+  [[ "$DOC_JOB_SHORT" -eq 1 ]] && DOC_NAME="$JOB_SHORT"
+
+  DOC_FILE="$DOC_TMP${JOB_GROUP}/$DOC_NAME${DOC_TYPE}"
+  DOC_LINK="$DOC_WIKI${JOB_GROUP}/$DOC_NAME"
+
+  if [[ "$DOC_CLONE" -eq 1 ]]
+  then
+    echo "CLONE DOCUMENTATION REPOSITORY $MSK_URL"
+    git clone "$DOC_URL" "$DOC_TMP" || die "FAIL CLONE $MSK_URL"
+  fi
+
+  if [[ "$DOC_CHECK" -eq 1 ]]
+  then
+
+    [[ -e "$DOC_FILE" ]] \
+    || die "NOT FOUND DOC FOR $JOB_NAME IN $DOC_FILE, \
+TRY WRITE IN $DOC_LINK"
+
+  fi
 
   echo "SEND JOB_TEMPLATE $JOB_TEMPLATE"
   echo "awx-cli send $JOB_TEMPLATE" | bash \
