common: update awx-common
  @ 00:05 hs

diff --git a/awx-common b/awx-common
--- a/awx-common
+++ b/awx-common
@@ -16,6 +16,12 @@
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
+# shellcheck disable=SC2016
+# shellcheck disable=SC2028
+# shellcheck disable=SC2034
+# shellcheck disable=SC2046
+# shellcheck disable=SC2086
+
 RED="$(tput setaf 196)"
 GREEN="$(tput setaf 46)"
 DIR_REAL="$(realpath "$DIR_BIN")"
@@ -25,14 +31,14 @@ BIN=$(basename "$0")
 
 die ()
 {
-  printf "%s\n" "${RED}[ERROR] $1 $NORMAL" && exit 1
+  printf "%s\\n" "${RED}[ERROR] $1 $NORMAL" && exit 1
 }
 
 log ()
 {
   local NOW
   NOW="$(date +'%F %T')"
-  printf "%s\n" "${NORMAL}${NOW} [INFO] $1 $NORMAL"
+  printf "%s\\n" "${NORMAL}${NOW} [INFO] $1 $NORMAL"
 }
 
 log_send_file()
@@ -43,7 +49,7 @@ log_send_file()
 
 success ()
 {
-  printf "%s\n" "${GREEN}[OK] $1 $NORMAL" && exit 1
+  printf "%s\\n" "${GREEN}[OK] $1 $NORMAL" && exit 0
 }
 
 stderror ()
@@ -88,6 +94,16 @@ code()
 title1()
 {
   printf "\\n# %s\\n\\n" "$1"
+}
+
+title2()
+{
+  printf "\\n## %s\\n\\n" "$1"
+}
+
+title3()
+{
+  printf "\\n### %s\\n\\n" "$1"
 }
 
 get_file_list()
@@ -141,11 +157,11 @@ filelist_send_all()
   [[   -z "$1" ]] && exit 1
   [[ ! -e "$1" ]] && exit 1
 
-  cat "$1" | while read -r FILE
+  while read -r FILE
   do
     log_send_file "$FILE"
     echo awx-cli send $AWX_DEBUG "$FILE" | bash
-  done
+  done < "$1"
 
 }
 
@@ -208,6 +224,35 @@ host_associate()
     --group "$2"
 }
 
+host_list_enabled()
+{
+
+awx-cli host list  \
+  --inventory "$1" \
+  --enabled true   \
+  --all-pages      \
+  --format id      \
+  | tr ' ' '\n'    \
+  | grep -vE '^$'
+
+}
+
+inventory_get_id()
+{
+  awx-cli inventory get \
+    --format id         \
+    --name "$1"
+}
+
+host_disable()
+{
+  awx-cli host modify   \
+    --enabled false     \
+    --inventory "$1"    \
+    --format human "$2"
+}
+
+
 log_ansible_proxmox_kvm()
 {
 
@@ -221,7 +266,7 @@ log_ansible_proxmox_kvm()
     HOST="$(echo "$LINE" | awk '{print $4}')"
     VMID="$(echo "$LINE" | grep -oE 'vmid=[0-9]+')"
     STATE="$(echo "$LINE" | grep -oE 'state=[a-z]+')"
-    printf "%s %s ansible-proxmox_kvm: %s %s\n" "$DATE" "$HOST" "$VMID" "$STATE"
+    printf "%s %s ansible-proxmox_kvm: %s %s\\n" "$DATE" "$HOST" "$VMID" "$STATE"
   done
 
 }
@@ -261,7 +306,7 @@ awx_ad_hoc_shell_launch()
 
 awx_ad_hoc_shell_footer()
 {
-  echo "\n\`\`\`"
+  echo "\\n\`\`\`"
 }
 
 awx_ad_hoc_shell()
@@ -288,7 +333,7 @@ wait_seconds()
 
   [[ ! -z "$2" ]] && S="$2"
 
-  for i in $(seq $S -1 0)
+  for i in $(seq "$S" -1 0)
   do
     echo "wait $i seconds to find and send all $1... "
     sleep 1
@@ -300,7 +345,7 @@ filelist_total()
   local TOTAL
 
   TOTAL="$(wc -l "$1" | cut -d' ' -f1)"
-  printf "found %s %s\n" "$TOTAL" "$2"
+  printf "found %s %s\\n" "$TOTAL" "$2"
 }
 
 function get_json()
@@ -327,29 +372,42 @@ function get_json()
   awx-cli receive --$1 "$2" > "$JSON"
 }
 
+json_get_unified_job_name()
+{
+  local JQ
+
+  JQ='.[] | .asset_relation | .workflow_nodes | .[] | .unified_job_name'
+  jq -r "$JQ" "$1"
+}
+
 function get_json_workflows()
 {
-  local FILE
+  local TMP
 
-  awx-json-get-unified-job-name "$1" \
-    | grep "$WORKFLOW_PREFIX" \
-    | while read -r FILE
+  json_get_unified_job_name "$1" | grep "$WORKFLOW_PREFIX" \
+    | while read -r i
       do
-        get_json_workflows "$DIR_WORKFLOW/$FILE.json"
+        json_get_unified_job_name "$DIR_WORKFLOW/$i.json" \
+          | grep "$WORKFLOW_PREFIX"  \
+          | while read -r j
+            do
+              json_get_unified_job_name "$DIR_WORKFLOW/$j.json"
+              echo "$j"
+            done
+        echo "$i"
       done
-
   echo "$1"
 }
 
 function get_url()
 {
-  local PATH
+  local P
 
-  [[ "$1" = 'project'      ]] && PATH='#/projects/'
-  [[ "$1" = 'job_template' ]] && PATH='#/templates/job_template'
-  [[ "$1" = 'workflow'     ]] && PATH='#/templates/workflow_job_template'
+  [[ "$1" = 'project'      ]] && P='#/projects/'
+  [[ "$1" = 'job_template' ]] && P='#/templates/job_template'
+  [[ "$1" = 'workflow'     ]] && P='#/templates/workflow_job_template'
 
-  printf "%s/%s/%s" "$AWX_CFG_HOST" "$PATH" "$2"
+  printf "%s/%s/%s" "$AWX_CFG_HOST" "$P" "$2"
 }
 
 project_get_id()
@@ -360,6 +418,18 @@ project_get_id()
 job_template_get_id()
 {
   [[ -z "$1" ]] || awx-cli job_template get -n "$1" -f id
+}
+
+jq_yq_modify()
+{
+  jq empty "$1" 2>/dev/null
+
+  if [[ "$?" -eq 0 ]]
+  then
+    jq -r ".$2=\"$3\"" "$1" | sponge "$1"
+  else
+    yq -r ".$2=\"$3\"" "$1" | sponge "$1"
+  fi
 }
 
 AWX_CFG_HOST="$(awx_cfg_get_host)"
