awx-credential-create: fix invalid ssh_key_data
  @ 01:00 hs

diff --git a/awx-credential-create b/awx-credential-create
--- a/awx-credential-create
+++ b/awx-credential-create
@@ -96,9 +96,9 @@ then
 
   if ssh-keygen -lf "$TMP" >/dev/null 2>/dev/null
   then
-    SSH_KEY_DATA="$(cat "$TMP")"
+    SSH_KEY_FILE="$TMP"
   else
-    die "INVALID $PASS_KEY_DATA"
+    die "INVALID $PASS_KEY_DATA in $TMP"
   fi
 
   [[ "$?" -ne 0      ]] && die "NOT FOUND $PASS_KEY_DATA"
@@ -116,16 +116,17 @@ else
   SSH_KEY_FILE="$2"
   [[ -e "$SSH_KEY_FILE" ]] || die "NOT FOUND FILE: $SSH_KEY_FILE"
 
-  if ssh-keygen -lf "$SSH_KEY_FILE" >/dev/null 2>/dev/null
+  if ! ssh-keygen -lf "$SSH_KEY_FILE" >/dev/null 2>/dev/null
   then
-    SSH_KEY_DATA="$(cat "$SSH_KEY_FILE")"
-  else
     die "INVALID $SSH_KEY_FILE"
   fi
 
   [[ -z "$3" ]] || SSH_KEY_UNLOCK="$3"
 
 fi
+
+# https://liquidat.wordpress.com/2019/05/05/howto-adding-ssh-keys-to-ansible-tower-via-tower-cli/
+SSH_KEY_DATA="$(sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' "$SSH_KEY_FILE")"
 
 [[ -z "$SSH_KEY_DATA" ]] && die "NOT FOUND SSH_KEY_DATA"
 
@@ -145,7 +146,7 @@ else
 CREDENTIAL_INPUT="$(cat << EOF
 {
   "username": "$CRED_USER",
-  "ssh_key_data": "$SSH_KEY_DATA\n",
+  "ssh_key_data": "$SSH_KEY_DATA",
   "ssh_key_unlock": "$SSH_KEY_UNLOCK"
 }
 EOF
