awx-deploy-revision: add git reset --hard when GIT_RESET_HARD_REVISION is defined
  @ 00:09 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -71,6 +71,12 @@ then
   git checkout "$REVISION" || die "FAILED TO CHECKOUT $REVISION"
 fi
 
+if [[ -n "$GIT_RESET_HARD_REVISION" ]]
+then
+  git reset --hard "origin/$REVISION" \
+    || die "FAILED TO HARD RESET $REVISION"
+fi
+
 REVISION_TYPE="$(git cat-file -t "$REVISION")"
 
 if [[ "$REVISION_TYPE" != 'tag' ]]
