awx-deploy-revision: prevent execute git pull when revision is a tag
  @ 00:20 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -71,7 +71,14 @@ then
   git checkout "$REVISION" || die "FAILED TO CHECKOUT $REVISION"
 fi
 
-git pull                   || die "FAILED TO PULL $REVISION"
+REVISION_TYPE="$(git cat-file -t "$REVISION")"
+
+if [[ "$REVISION_TYPE" != 'tag' ]]
+then
+
+  git pull                 || die "FAILED TO PULL $REVISION"
+
+fi
 
 [[ -d "$DEPLOY_DIR"     ]] || die "NOT FOUND DIR $DEPLOY_DIR"
 [[ -e "$DEPLOY_FILE"    ]] || die "NOT FOUND FILE $DEPLOY_FILE"
