awx-deploy-grant: execute git fetch only when DONT_FETCH=0, define DONT_FETCH=0 as default
  @ 00:05 hs

diff --git a/awx-deploy-grant b/awx-deploy-grant
--- a/awx-deploy-grant
+++ b/awx-deploy-grant
@@ -84,8 +84,12 @@ CURRENT_BRANCH="$(git branch --no-color | grep '^\* ' | cut -d ' ' -f2)"
 [[ -z "$REVISION"       ]] && REVISION="$CURRENT_BRANCH"
 [[ -n "$VALID_TYPE"     ]] || VALID_TYPE='(admin|read|member|execute|adhoc|update|use|auditor|project_admin|inventory_admin|credential_admin|workflow_admin|notification_admin|job_template_admin)'
 [[ -n "$DONT_PULL"      ]] || DONT_PULL=0
+[[ -n "$DONT_FETCH"     ]] || DONT_FETCH=0
 
-git fetch                  || die "FAILED TO FECTH"
+if [[ "$DONT_FETCH" -eq 0 ]]
+then
+  git fetch                  || die "FAILED TO FECTH"
+fi
 
 if [[ "$CURRENT_BRANCH" != "$REVISION" ]]
 then
