awx-deploy-grant: add support for multiple GRANT TYPES
  @ 00:10 hs

diff --git a/awx-deploy-grant b/awx-deploy-grant
--- a/awx-deploy-grant
+++ b/awx-deploy-grant
@@ -82,6 +82,7 @@ cd "$AWX_DIR"              || die "FAILED TO CHANGE TO AWX DIR"
 [[ -d '.git'            ]] || die "NOT FOUND GIT REPOSITORY"
 CURRENT_BRANCH="$(git branch --no-color | grep '^\* ' | cut -d ' ' -f2)"
 [[ -z "$REVISION"       ]] && REVISION="$CURRENT_BRANCH"
+[[ -n "$VALID_TYPE"     ]] || VALID_TYPE='(admin|read|member|execute|adhoc|update|use|auditor|project_admin|inventory_admin|credential_admin|workflow_admin|notification_admin|job_template_admin)'
 
 git fetch                  || die "FAILED TO FECTH"
 
@@ -143,22 +144,26 @@ echo "$DEFAULT_TEAM_DEPLOY" \
 
       # use default grant permission defined in config
       RESOURCE="GRANT_${D^^}"
-      TYPE="${!RESOURCE}"
+      TYPES="${!RESOURCE}"
 
       # use team grant permission defined in config
       TEAM_GRANT="${TEAM//-/}_GRANT_${D^^}"
       TEAM_GRANT="${TEAM_GRANT^^}"
       GRANT_TYPE="${!TEAM_GRANT}"
-      [[ -z "$GRANT_TYPE" ]] || TYPE="$GRANT_TYPE"
+      [[ -z "$GRANT_TYPE" ]] || TYPES="$GRANT_TYPE"
 
-      [[ -z "$TYPE" ]] && die "UNDEFINED DEFAULT_$RESOURCE IN $AWX_CFG"
+      [[ -z "$TYPES" ]] && die "UNDEFINED DEFAULT_$RESOURCE IN $AWX_CFG"
 
-      printf "%-13s %-*s %-8s %-20s\\n"           \
-             "$D" "$COLF" "$NAME" "$TYPE" "$TEAM" | sed 's/ \+$//g'
+      echo "$TYPES" | tr ' ' '\n' | while read -r TYPE
+      do
+        [[ "$TYPE" =~ $VALID_TYPE ]] \
+          || die "INVALID TYPE $TYPE FOR $D $NAME TEAM $TEAM"
+        printf "%-13s %-*s %-8s %-20s\\n"           \
+               "$D" "$COLF" "$NAME" "$TYPE" "$TEAM" | sed 's/ \+$//g'
+      done
 
     done < "$TMP"
 
   done | tee "$OUT"
 
 rm -f "$TMP"
-
