awx-deploy-revoke: don't execute git fetch DONT_FETCH is enabled
  @ 00:04 hs

diff --git a/awx-deploy-revoke b/awx-deploy-revoke
--- a/awx-deploy-revoke
+++ b/awx-deploy-revoke
@@ -77,6 +77,7 @@ exit 0
 [[ -d "$AWX_DIR"        ]] || die "NOT FOUND AWX DIR"
 [[ -z "$DEPLOY_DIR"     ]] && DEPLOY_DIR='deploy'
 [[ -n "$DONT_CHECKOUT"  ]] || DONT_CHECKOUT=0
+[[ -n "$DONT_FETCH"     ]] || DONT_FETCH=0
 [[ -n "$DONT_PULL"      ]] || DONT_PULL=0
 
 cd "$AWX_DIR"              || die "FAILED TO CHANGE TO AWX DIR"
@@ -85,7 +86,12 @@ CURRENT_BRANCH="$(git branch --no-color | grep '^\* ' | cut -d ' ' -f2)"
 [[ -z "$REVISION"       ]] && REVISION="$CURRENT_BRANCH"
 [[ -n "$VALID_TYPE"     ]] || VALID_TYPE='(admin|read|member|execute|adhoc|update|use|auditor|project_admin|inventory_admin|credential_admin|workflow_admin|notification_admin|job_template_admin)'
 
-git fetch                  || die "FAILED TO FECTH"
+if [[ "$DONT_FETCH" -eq 0 ]]
+then
+
+  git fetch || die "FAILED TO FECTH"
+
+fi
 
 if [[ "$CURRENT_BRANCH" != "$REVISION" ]]
 then
