awx-credential-modify: fix invalid ssh_key_data
  @ 00:30 hs

diff --git a/awx-credential-modify b/awx-credential-modify
--- a/awx-credential-modify
+++ b/awx-credential-modify
@@ -85,6 +85,7 @@ ID="$(awx-cli credential get -n "$CREDENTIAL" -f id)"
 [[ -z "$CREDENTIAL_TYPE"         ]] && die "UNDEFINED CREDENTIAL_TYPE"
 
 export PASSWORD_STORE_DIR="$PASSWORD_STORE_DIR"
+TMP="$(mktemp)"
 
 if [[ -z "$2" ]]
 then
@@ -94,7 +95,15 @@ then
   PASS_KEY_UNLOCK="${PASS_CRED_PREFIX}/ssh_key_unlock"
   PASS_KEY_USER="${PASS_CRED_PREFIX}/username"
 
-  SSH_KEY_DATA="$(pass "$PASS_KEY_DATA")"
+  pass "$PASS_KEY_DATA" > "$TMP" && chmod 0600 "$TMP"
+
+  if ssh-keygen -lf "$TMP" >/dev/null 2>/dev/null
+  then
+    SSH_KEY_FILE="$TMP"
+  else
+    die "INVALID $PASS_KEY_DATA in $TMP"
+  fi
+
   [[ "$?" -ne 0      ]] && die "NOT FOUND $PASS_KEY_DATA"
   [[ -z "$3"         ]] && SSH_KEY_UNLOCK="$(pass "$PASS_KEY_UNLOCK")"
   [[ "$?" -ne 0      ]] && die "NOT FOUND $PASS_KEY_UNLOCK"
@@ -109,11 +118,18 @@ else
 
   SSH_KEY_FILE="$2"
   [[ -e "$SSH_KEY_FILE" ]] || die "NOT FOUND FILE: $SSH_KEY_FILE"
-  SSH_KEY_DATA="$(cat "$SSH_KEY_FILE")"
+
+  if ! ssh-keygen -lf "$SSH_KEY_FILE" >/dev/null 2>/dev/null
+  then
+    die "INVALID $SSH_KEY_FILE"
+  fi
 
   [[ -z "$3" ]] || SSH_KEY_UNLOCK="$3"
 
 fi
+
+# https://liquidat.wordpress.com/2019/05/05/howto-adding-ssh-keys-to-ansible-tower-via-tower-cli/
+SSH_KEY_DATA="$(sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' "$SSH_KEY_FILE")"
 
 [[ -z "$SSH_KEY_DATA" ]] && die "NOT FOUND SSH_KEY_DATA"
 
@@ -146,3 +162,5 @@ awx-cli credential modify              \
   --name "$CREDENTIAL"                 \
   --organization "$ORGANIZATION"       \
   --inputs "$CREDENTIAL_INPUT"     "$ID"
+
+rm -f "$TMP"
