add useful scripts and fix syntax to prevent lint errors with shellcheck
 @ 01:10 hs

diff --git a/awx-common b/awx-common
--- a/awx-common
+++ b/awx-common
@@ -37,6 +37,11 @@ success ()
   printf "%s\n" "${GREEN}[OK] $1 $NORMAL" && exit 1
 }
 
+stderror ()
+{
+  echo >&2 "$1"
+}
+
 [[ ! -e "$AWX_CONFIG" ]] && die "NOT FOUND FILE: $AWX_CONFIG"
 
 eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$AWX_CONFIG" | while read -r k v
@@ -44,6 +49,16 @@ do
     str="$k='$v'"
     echo "$str"
 done)
+
+[[ -z "$HTTP_PROXY" ]] || stderror "Using HTTP_PROXY=$HTTP_PROXY"
+
+# check dependencies
+
+for i in awx-cli jq yq
+do
+  command -v "$i" >/dev/null || die "try: pip install $i " \
+    | sed 's/awx-cli/ansibel-tower-cli/g'
+done
 
 get_file_list()
 {
@@ -127,3 +142,70 @@ host_associate()
     --host "$1"          \
     --group "$2"
 }
+
+log_ansible_proxmox_kvm()
+{
+
+  [[ ! -e "$1" ]] && die "NOT FOUND FILE $1"
+
+  local DATE HOST VMID STATE
+
+  grep 'ansible-proxmox_kvm:' "$1" | while read -r LINE
+  do
+    DATE="$(echo "$LINE" | cut -c -15)"
+    HOST="$(echo "$LINE" | awk '{print $4}')"
+    VMID="$(echo "$LINE" | grep -oE 'vmid=[0-9]+')"
+    STATE="$(echo "$LINE" | grep -oE 'state=[a-z]+')"
+    printf "%s %s ansible-proxmox_kvm: %s %s\n" "$DATE" "$HOST" "$VMID" "$STATE"
+  done
+
+}
+
+project_update()
+{
+  awx-cli project update -n "$1" $AWX_DEBUG
+}
+
+awx_ad_hoc_shell_header()
+{
+  local INVENTORY LIMIT COMMAND TITLE MSG
+  INVENTORY="$1"
+  LIMIT="$2"
+  COMMAND="$3"
+  TITLE="$4"
+
+MSG=$(cat << EOF
+## Ejecutar %s en %s" "$TITLE" "$LIMIT"
+
+\`\`\`
+
+  # awx-ad-hoc-shell "$INVENTORY" "$LIMIT" "$COMMAND""
+
+EOF
+)
+
+echo "$MSG"
+
+}
+
+awx_ad_hoc_shell_launch()
+{
+  "$INVENTORY" "$LIMIT" "$COMMAND"
+  awx-ad-hoc-shell "$INVENTORY" "$LIMIT" "$COMMAND"
+}
+
+awx_ad_hoc_shell_footer()
+{
+  echo "\n\`\`\`"
+}
+
+awx_ad_hoc_shell()
+{
+  local INVENTORY LIMIT COMMAND TITLE
+
+awx_ad_hoc_shell_header "$INVENTORY" "$LIMIT" "$COMMAND" "$TITLE"
+awx_ad_hoc_shell_launch "$INVENTORY" "$LIMIT" "$COMMAND"
+awx_ad_hoc_shell_footer
+
+}
+
diff --git a/awx-host-enable-all b/awx-host-enable-all
--- a/awx-host-enable-all
+++ b/awx-host-enable-all
@@ -21,22 +21,15 @@
 DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"
 
 [[ -z "$1" ]] && die "EMPTY INVENTORY"
+
 INVENTORY="$1"
+HOSTS="hosts-$INVENTORY"
 
-[[ -z "$2" ]] && die "EMPTY LIMIT"
-LIMIT="$2"
+[[ -e "$HOSTS" ]] || die "NOT FOUND $HOSTS"
 
-REGEXP='s(pxe|ans|apt|prn|ftp|cdn|git|log|rep)01f[0-9]+'
-[[ -z "$3" ]] || REGEXP="$3"
+AWX_ENABLE="awx-cli host modify --enabled true -i $INVENTORY"
 
-COMMAND="sudo /usr/sbin/qm list | grep stopped | grep -E \"$REGEXP\" | while read ID HOST _;do echo \$HOST && /usr/sbin/qm start \$ID;sleep 5;done"
-
-echo "\`\`\`"
-echo
-echo "  # awx-ad-hoc-shell $INVENTORY $LIMIT $COMMAND"
-echo
-
-awx-ad-hoc-shell "$INVENTORY" "$LIMIT" "$COMMAND"
-
-echo
-echo "\`\`\`"
+grep -i "$INVENTORY" "$HOSTS" | grep -v '\[' | while read -r HOST
+do
+  $AWX_ENABLE -n "$HOST"
+done
