awx-deploy-revision: improve message error when fail checkout REVISION
  @ 00:02 hs

diff --git a/awx-deploy-revision b/awx-deploy-revision
--- a/awx-deploy-revision
+++ b/awx-deploy-revision
@@ -167,7 +167,8 @@ fi
 if [[ "$CURRENT_BRANCH" != "$REVISION" ]]
 then
   printf "GIT CHECKOUT REVISION %s\\n" "$REVISION"
-  git checkout "$REVISION" || die "FAILED TO CHECKOUT $REVISION"
+  git checkout "$REVISION" \
+    || die "FAILED TO CHECKOUT $REVISION TRY GIT_STRATEGY: clone"
 fi
 
 if [[ "$GIT_RESET_HARD_REVISION" -eq 1 ]]
